import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import PropTypes from "prop-types";
import gsap from "gsap";
import "./DepthCarousel.css";

const clamp = (value, min, max) => Math.min(Math.max(value, min), max);

export default function DepthCarousel({ items, cardWidth=340, cardHeight=440, depth=210, spread=96, tilt=18, perspective=1500, visibleCards=3, falloff=.16, blur=4, duration=720, autoplay=true, autoplayDelay=5600, onChange }) {
  const data=useMemo(()=>Array.isArray(items)?items:[],[items]);
  const rootRef=useRef(null);const cardRefs=useRef([]);const overlayRefs=useRef([]);const posRef=useRef(0);const focusRef=useRef(0);const tweenRef=useRef(null);const scaleRef=useRef(1);const cfgRef=useRef({});const dragRef=useRef(null);const wheelTimerRef=useRef(null);const autoTimerRef=useRef(null);const reducedRef=useRef(false);const visibleRef=useRef(true);const pageVisibleRef=useRef(!document.hidden);const onChangeRef=useRef(onChange);const [active,setActive]=useState(0);
  onChangeRef.current=onChange;cfgRef.current={count:data.length,depth,spread,tilt,visibleCards,falloff,blur,duration,cardWidth,autoplayDelay};
  const layout=useCallback((position)=>{const cfg=cfgRef.current;if(!cfg.count)return;for(let index=0;index<cfg.count;index++){const element=cardRefs.current[index];if(!element)continue;let distance=index-position;distance=((distance%cfg.count)+cfg.count)%cfg.count;if(distance>cfg.count/2)distance-=cfg.count;const back=Math.max(0,distance);const shown=Math.abs(distance)<=cfg.visibleCards+.5;const opacity=shown?(distance<0?Math.max(0,1+distance):1):0;element.style.transform=`translate(-50%, -50%) scale(${scaleRef.current}) translateX(${(cfg.spread*distance).toFixed(2)}px) translateZ(${(-cfg.depth*distance).toFixed(2)}px) rotateY(${(cfg.tilt*clamp(distance,0,1)).toFixed(2)}deg)`;element.style.opacity=opacity.toFixed(3);element.style.filter=`brightness(${Math.max(.28,1-back*cfg.falloff).toFixed(3)}) blur(${Math.min(cfg.blur,(back/Math.max(1,cfg.visibleCards))*cfg.blur).toFixed(2)}px)`;element.style.zIndex=String(Math.round(2000-distance*20));element.style.pointerEvents=shown&&opacity>.05?"auto":"none";if(overlayRefs.current[index])overlayRefs.current[index].style.opacity=clamp(back*cfg.falloff*1.25,0,.75).toFixed(3);}},[]);
  const notify=useCallback((index)=>{setActive(index);onChangeRef.current?.(index,data[index]);},[data]);
  const tweenTo=useCallback((target,animate)=>{tweenRef.current?.kill();const proxy={position:posRef.current};tweenRef.current=gsap.to(proxy,{position:target,duration:animate&&!reducedRef.current?cfgRef.current.duration/1000:0,ease:"power3.out",onUpdate:()=>{posRef.current=proxy.position;layout(proxy.position);},onComplete:()=>{const count=cfgRef.current.count;if(count)posRef.current=((posRef.current%count)+count)%count;layout(posRef.current);}});},[layout]);
  const setFocus=useCallback((rawIndex,animate=true)=>{const count=cfgRef.current.count;if(!count)return;const index=((rawIndex%count)+count)%count;let delta=index-posRef.current;delta=((delta%count)+count)%count;if(delta>count/2)delta-=count;tweenTo(posRef.current+delta,animate);if(index!==focusRef.current){focusRef.current=index;notify(index);}},[notify,tweenTo]);
  const navigateBy=useCallback((step)=>setFocus(focusRef.current+step,true),[setFocus]);
  useEffect(()=>{const root=rootRef.current;if(!root)return undefined;const observer=new ResizeObserver(([entry])=>{const needed=cfgRef.current.cardWidth+Math.abs(cfgRef.current.spread)*2+140;scaleRef.current=clamp(entry.contentRect.width/needed,.58,1);layout(posRef.current);});observer.observe(root);return()=>observer.disconnect();},[layout]);
  useEffect(()=>{const root=rootRef.current;if(!root)return undefined;const onWheel=(event)=>{if(cfgRef.current.count<2)return;event.preventDefault();tweenRef.current?.kill();const raw=Math.abs(event.deltaX)>Math.abs(event.deltaY)?event.deltaX:event.deltaY;posRef.current+=clamp(raw/(cfgRef.current.cardWidth*.9),-.55,.55);layout(posRef.current);clearTimeout(wheelTimerRef.current);wheelTimerRef.current=setTimeout(()=>setFocus(Math.round(posRef.current)),140);};root.addEventListener("wheel",onWheel,{passive:false});return()=>{root.removeEventListener("wheel",onWheel);clearTimeout(wheelTimerRef.current);};},[layout,setFocus]);
  const onPointerDown=useCallback((event)=>{if(cfgRef.current.count<2)return;tweenRef.current?.kill();dragRef.current={x:event.clientX,start:posRef.current,lastX:event.clientX,lastTime:performance.now(),velocity:0,moved:false,id:event.pointerId};},[]);
  const onPointerMove=useCallback((event)=>{const drag=dragRef.current;if(!drag)return;const dx=event.clientX-drag.x;if(!drag.moved&&Math.abs(dx)>4){drag.moved=true;rootRef.current?.setPointerCapture(drag.id);}if(!drag.moved)return;const now=performance.now();drag.velocity=(event.clientX-drag.lastX)/Math.max(now-drag.lastTime,1);drag.lastX=event.clientX;drag.lastTime=now;posRef.current=drag.start-dx/Math.max(cfgRef.current.cardWidth*.55*scaleRef.current,40);layout(posRef.current);},[layout]);
  const onPointerEnd=useCallback(()=>{const drag=dragRef.current;if(!drag)return;dragRef.current=null;if(!drag.moved)return;const projected=posRef.current-(drag.velocity*180)/Math.max(cfgRef.current.cardWidth*.55*scaleRef.current,40);setFocus(Math.round(projected));},[setFocus]);
  const onKeyDown=useCallback((event)=>{if(event.key==="ArrowLeft"||event.key==="ArrowRight"){event.preventDefault();navigateBy(event.key==="ArrowLeft"?-1:1);}},[navigateBy]);
  useEffect(()=>{reducedRef.current=window.matchMedia("(prefers-reduced-motion: reduce)").matches;if(!autoplay||reducedRef.current||data.length<2)return undefined;const root=rootRef.current;let hovered=false,focused=false;const stop=()=>{clearInterval(autoTimerRef.current);autoTimerRef.current=null;};const start=()=>{stop();if(!visibleRef.current||!pageVisibleRef.current)return;autoTimerRef.current=window.setInterval(()=>{if(!hovered&&!focused)navigateBy(1);},Math.max(cfgRef.current.autoplayDelay,3000));};const visibilityObserver=new IntersectionObserver(([entry])=>{visibleRef.current=entry.isIntersecting;entry.isIntersecting?start():stop();});visibilityObserver.observe(root);const onVisibility=()=>{pageVisibleRef.current=!document.hidden;pageVisibleRef.current?start():stop();};const onEnter=()=>{hovered=true;};const onLeave=()=>{hovered=false;};const onFocusIn=()=>{focused=true;};const onFocusOut=()=>{focused=false;};document.addEventListener("visibilitychange",onVisibility);root.addEventListener("mouseenter",onEnter);root.addEventListener("mouseleave",onLeave);root.addEventListener("focusin",onFocusIn);root.addEventListener("focusout",onFocusOut);start();return()=>{stop();visibilityObserver.disconnect();document.removeEventListener("visibilitychange",onVisibility);root.removeEventListener("mouseenter",onEnter);root.removeEventListener("mouseleave",onLeave);root.removeEventListener("focusin",onFocusIn);root.removeEventListener("focusout",onFocusOut);};},[autoplay,data.length,navigateBy]);
  useEffect(()=>{layout(posRef.current);},[layout,depth,spread,tilt,visibleCards,falloff,blur,cardWidth,cardHeight,data.length]);
  useEffect(()=>()=>{tweenRef.current?.kill();clearTimeout(wheelTimerRef.current);clearInterval(autoTimerRef.current);},[]);
  return <div ref={rootRef} className="depth-carousel" style={{"--dc-perspective":`${perspective}px`}} role="region" aria-roledescription="carrusel" aria-label="Panorama energético" tabIndex={0} onPointerDown={onPointerDown} onPointerMove={onPointerMove} onPointerUp={onPointerEnd} onPointerCancel={onPointerEnd} onKeyDown={onKeyDown}>
    <div className="depth-carousel__stage">{data.map((item,index)=><article key={item.title} ref={(node)=>{cardRefs.current[index]=node;}} className="depth-carousel__card" style={{width:cardWidth,height:cardHeight}} aria-roledescription="slide" aria-label={`${index+1} de ${data.length}: ${item.title}`} aria-hidden={active!==index} onClick={()=>setFocus(index)}><img className="depth-carousel__img" src={item.image} alt={item.alt} width="1000" height="1250" loading="lazy" draggable={false}/><span ref={(node)=>{overlayRefs.current[index]=node;}} className="depth-carousel__tint"/><div className="depth-carousel__content"><small>{item.category}</small><h3>{item.title}</h3><p>{item.description}</p></div></article>)}</div>
    <button type="button" className="depth-carousel__arrow depth-carousel__arrow--prev" aria-label="Escena anterior" onClick={()=>navigateBy(-1)}>‹</button><button type="button" className="depth-carousel__arrow depth-carousel__arrow--next" aria-label="Escena siguiente" onClick={()=>navigateBy(1)}>›</button>
    <div className="depth-carousel__dots" aria-label="Escenas">{data.map((item,index)=><button key={item.title} type="button" aria-label={`Ir a ${item.title}`} aria-current={active===index?"true":undefined} className={`depth-carousel__dot${active===index?" is-active":""}`} onClick={()=>setFocus(index)}/>)}</div>
  </div>;
}
DepthCarousel.propTypes={items:PropTypes.arrayOf(PropTypes.shape({image:PropTypes.string.isRequired,alt:PropTypes.string.isRequired,category:PropTypes.string.isRequired,title:PropTypes.string.isRequired,description:PropTypes.string.isRequired})).isRequired,cardWidth:PropTypes.number,cardHeight:PropTypes.number,depth:PropTypes.number,spread:PropTypes.number,tilt:PropTypes.number,perspective:PropTypes.number,visibleCards:PropTypes.number,falloff:PropTypes.number,blur:PropTypes.number,duration:PropTypes.number,autoplay:PropTypes.bool,autoplayDelay:PropTypes.number,onChange:PropTypes.func};
